-- Run this script as SYS user (or another DBA user), not as USOS.
-- Example:
-- sqlplus sys/<SYS_PASSWORD>@//localhost:1521/FREEPDB1 as sysdba

WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
    EXECUTE IMMEDIATE 'DROP USER USOS CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER USOS IDENTIFIED BY usos123;

ALTER USER USOS
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO USOS;
GRANT CREATE TABLE TO USOS;
GRANT CREATE VIEW TO USOS;
GRANT CREATE SEQUENCE TO USOS;
GRANT CREATE TRIGGER TO USOS;
GRANT CREATE PROCEDURE TO USOS;

